name: Mobile Tests
on: [push, pull_request]

jobs:
  mobile_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Tests
      run: go test -tags ci,mobile ./...

